### ISSUE TITLE
Trying to reuse some code

### ISSUE THREAD

**Issue by JQFonseca** [LightForm-group/xrdfit#10]
Hi Peter,

I am trying to reuse some of this code for a final year project student and to analyse XRD data. When I try to use your pv_fit function, without parameters it calls a guess function. One of the arguments is maxima_range, which should be a dict.  However, at the start of the function the number of peaks is calculated by taking modulus 2 of this dictionary. If I only have one peak this gives zero, and then some parameters are not guessed.

`def guess_params(x_data, y_data, maxima_ranges: dict) -> lmfit.Parameters:

    """Given a dataset and some details about where the maxima are, guess some good initial
    values for the PV fit."""

    params = lmfit.Parameters()

    num_maxima = len(maxima_ranges) // 2

    for index in range(1, num_maxima + 1):

    ...`

Can you help? Do we have to do index iteration instead of iterating over the peak range dictionary? Doesn't seem very pythonic... Thanks!

**Comment by JQFonseca** [comment]
Actually, I understand what's happening now. But I still wonder why do it this way and lose the peak name in the dictionary instead of keeping it and iterating over it. Just curious.

**Comment by JQFonseca** [comment]
I understand what's going on now, sorry. I will ask you about your design choice in person!

**Comment by merrygoat** [comment]
Yes - this is much improved in the latest feature branch version!

I tend to start off making the user input all of the parameters manually to make sure the ideas work and then slowly remove them as I work out what can be calculated manually.

In this case we started off with different functions for singlet, doublet, triplet peaks etc. Then it got condensed into one function with a num_peaks parameter and like you say it now just works out num_maxima from the number of maxima_bounds provided.

I am trying to keep the tutorial notebooks up to date as I do stuff so they should reflect the latest changes.
