### ISSUE TITLE
Investigate multiprocessing

### ISSUE THREAD

**Issue by merrygoat** [LightForm-group/xrdfit#28]
Investigate the python multiprocessing module to thread the processing of peaks to improve performance.

**Comment by merrygoat** [comment]
I am investigating this on the `multiprocessing` branch.

I have not had any luck with this. It works in principle, spawning python interpreters as intended and it produces reasonable results. The problem is that it is considerably slower.

- Serial benchmark: 0:33
- Multiprocessing (1 core): 4:02
- Multiprocessing (2 core): 3:03
- Multiprocessing (8 core): 4:48

I note that 1 -> 2 cores shows an improvement so it is working. My machine has 4 cores so presumably at a pool of 8 they are fighting more than they are helping. 
I don't know whether this is just the natural overhead of the multiprocessing module and that the problem is unsuited to it or whether there is a weakness in my implementation. I thought it might be caused by passing FitSpectrum objects around but eliminating this by making `FitSpectrum._fit_peak` a static method in: 08b92d69e88a6f1af2c7fd7268215e9b9a5052dc did not fix this.

I'll ask around a bit but I'm not hopeful.

**Comment by merrygoat** [comment]
I made some progress on this - it is not the processing that is slow, I think it is returning the lmfit modelResult from the fitting function that is slow. I think it uses pickle to pass values between processes and becaus the modelResult is complex it takes a while to pickle - the same problem as in #30.

It will take a bit more learning about multiprocess but maybe I can write the result directly from the process or something.

**Comment by JQFonseca** [comment]
Peter, I think this now does what it needs to well enough. It's a niche
application and it's the fastest bit of the process. It doesn't need to be
any faster.

João

**Comment by merrygoat** [comment]
I agree that this is low priority. This is also partly interesting because it is something that I want to learn about and I think has a fairly wide range of applications!
