### ISSUE TITLE
'first_cake_angle'  changes numbering of cakes not cake orientation

### ISSUE THREAD

**Issue by christopher-daniel** [LightForm-group/xrdfit#35]
Changing the first_cake_angle is expected to change the orientation of the cakes in the plot_polar and highlight_cakes function. Instead, the cake orientation remains the same and the cakes are renumbered.

**Comment by merrygoat** [comment]
But isn't that the same thing? If you rotate the image and not the numbers, or the numbers and not the image that's equivalent.

The way we have it at the moment is how I interpreted first_cake_angle. The angle at which we want the number 1 on the diagram.

**Comment by christopher-daniel** [comment]
The first cake should always be the first column in the data, after caking the diffraction pattern image. Since this is a flat 2D detector, there is an 'up' direction and a 'horizontal' direction, which is related to the sample directions, and I would interpret first_cake_angle to mean the orientation for that first cake i.e. is the first cake aligned horizontally, or vertically, or in what direction. However, at the moment, the orientation of the first cake is fixed (horizontally) and changing the first_cake_angle is relabelling the columns, which is confusing.

**Comment by merrygoat** [comment]
Ah OK, there is a fixed relationship between the columns and the cake number. This means that both the image and the label should be rotated.

It was dead easy to rotate the figure but then it messed up the labels becuase the label transformation depends on the rotation of the figure. Should be sorted in 34e1f1d0eca178c1e6fdfb6a726d665c8680ffbf

**Comment by christopher-daniel** [comment]
Just tested and the cakes can now be rotated depending on the first_cake_angle, but the labels do not match up with the cakes. It seems that the cakes and cake numbering are being rotated in an opposite sense to each other. If 0 is vertical, cake numbering rotates clockwise with positive degrees, whereas the cake rotates away anti-clockwise.

**Comment by merrygoat** [comment]
OK, I had not worked out the details of matplotlib polar projection. Even when you set the data to be plotted clockwise the theta offset parameter (used to rotate data) is always anticlockwise. Also a theta_offset of 0, starts the plot at East not North! That should be fixed on develop now. This also explains why I was struggling so much with the labels before.

**Comment by christopher-daniel** [comment]
Yes, that's works well now, cake numbers are fixed and the cakes rotate in the 'correct' sense.
