### ISSUE TITLE
Missing merge_cakes in FitExperiment - error unhelpful

### ISSUE THREAD

**Issue by christopher-daniel** [LightForm-group/xrdfit#37]
If merge_cakes is not included in FitEXperiment, the error is not correct in suggesting that the files cannot be found;

FileNotFoundError: No files found with file stub: '../data/sample_2_tension/Strain_{:05d}.dat'

Suggest give merge_cakes a default of 'False', so that single cakes can be fitted without including this input anyway.

**Comment by merrygoat** [comment]
It's a mandatory parameter so you should get: `__init__() missing 1 required positional argument: 'merge_cakes'` if you try and initialise a FitExperiment without the merge_cakes parameter.

Can you try and give an example code snippet that reproduces this?
