### ISSUE TITLE
consider a logging framework

### ISSUE THREAD

**Issue by mikapfl** [LightForm-group/xrdfit#44]
Hi,

during the review for JOSS, I noticed that you are using `print()` coupled with `verbose` und `debug` flags for logging. Maybe you could consider using a logging framework such as [the stdlib's logging](https://docs.python.org/3/library/logging.html) or [loguru](https://github.com/Delgan/loguru).

The benefit would be that users could configure the amount of logging in a standard way, and logging output goes to stderr by default instead of cluttering stdout which then stays open for other purposes.

Cheers

Mika

**Comment by merrygoat** [comment]
A good idea, thank you. I'm a bit lazy with logging and need to get into the habit of doing it properly.
