### ISSUE TITLE
Text and peak fits filling up notebook output during refinement

### ISSUE THREAD

**Issue by christopher-daniel** [LightForm-group/xrdfit#47]

**Comment by christopher-daniel** [comment]
Text with 'Diffraction pattern successfully loaded from file.' and plots showing what appear to be odd random fits are appearing in the output window when running a refinement. The plots also contain text describing the model used for peak fitting

![Screenshot 2020-07-30 at 09 52 24](https://user-images.githubusercontent.com/40835098/88903068-fbac3000-d24a-11ea-96fe-437b4e0a30fb.png)
.

**Comment by merrygoat** [comment]
Fixed in 9662a557db01ffc9e4db6380d038da32f38bd045. Sorry about that, they are debugging plots designed for diagnosing slow fits. With the switch to logging I forgot to put them in the debug mode.

**Comment by christopher-daniel** [comment]
No problem, all runs fine now.
