### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by mikapfl** [LightForm-group/xrdfit#49]
Hi,

is there any (semi-)automated way to test the software, to verify that my setup is correct and everything is installed as intended?

I haven't found anything in the docs, but maybe I am blind.

Cheers

Mika

**Comment by merrygoat** [comment]
I am treating the tutorial notebooks as a functional test as they cover all of the functions of the code. [I have set up a github Action](https://github.com/LightForm-group/xrdfit/actions) to test the notebooks using [treebeard](https://github.com/treebeardtech/treebeard) - this doesn't check the output of each cell in the notebook - just that they run without error. 

As for local testing for users, I could add a note to the documentation to run the tutorial notebooks. Do you think this is sufficient? 

I haven't used unit tests as I don't see how I can usefully add non-brittle tests. The output is figures based on fitting which is going to be variable. I could write tests to check the types of the input and output of each function but I don't see that this adds much over type hints and a type aware IDE.

**Comment by mikapfl** [comment]
that sounds great, thank you!

**Comment by alex-remedios** [comment]
Hey don't meant to intrude, Treebeard here.

Please be sure to feedback any pain points/feature gaps (e.g. with a better desktop experience). You can catch me on issues or gitter.

good luck!
