### ISSUE TITLE
FitSpectrum skips first row

### ISSUE THREAD

**Issue by schooft** [LightForm-group/xrdfit#55]
The "Basic analysis workflow" tutorial says about the file format:
> The data file does not have any column headings or title line.

However, `pandas.read_table` interprets the first line of a file as the header by default and therefore `FitSpectrum` effectively skips the first row:
```
from pathlib import Path
from xrdfit.spectrum_fitting import PeakParams, FitSpectrum 
Path("test.txt").write_text("1\t2\n3\t4\n")
FitSpectrum("test.txt").spectral_data  # array([[3, 4]])
```
This is probably not very important for most applications, but I found it surprising.

**Comment by merrygoat** [comment]
Good catch - thank you. Fixed in v1.2.1
