### ISSUE TITLE
Improve initial guess for fraction

### ISSUE THREAD

**Issue by merrygoat** [LightForm-group/xrdfit#8]
The fraction parameter (α) starts at 0.5 but ends up at 0.02. Need to check the upper and lower bounds over peaks of different shapes but it shouldn't be that different since it is just the Lorentzian/Gaussian ratio and the peaks are mostly the same. Changing this could reduce the number of iterations required for the fit.

**Comment by merrygoat** [comment]
Param specs are now all different! Performance will be improved by passing the previous peak params to the next instance in time so having good initial guesses might not be important at all as long as it converges eventually.

**Comment by JQFonseca** [comment]
The shape of the peak does change with deformation. This could be real and
meaningful/useful.

**Comment by merrygoat** [comment]
Experimentation showed that over constraining the fits made it slower so I guess it is best to just leave it to it!
